name: wuchuheng_route_parser
description: Routing Resolution Library.
version: 1.0.1
homepage: https://github.com/wuchuheng/wuchuheng_route_parser_dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
