name: Testing dart

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
